apiVersion: v1
kind: ConfigMap
metadata:
  name: task-board-config
  namespace: task-board
data:
  NODE_ENV: "production"
  HOST: "0.0.0.0"
  PORT: "3000"
  CORS_ORIGIN: "http://localhost:5173"
  AUTH0_AUDIENCE: "https://taskboard-api"

